# Generated by Django 4.0.2 on 2022-02-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntodeinteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('imagen_destacada', models.CharField(default='', max_length=100)),
                ('horario', models.CharField(default='', max_length=500)),
                ('descripcion', models.CharField(default='', max_length=1000)),
                ('imagenes', models.CharField(default='', max_length=1000)),
                ('videos', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
