# Generated by Django 4.0.2 on 2022-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='puntodeinteres',
            name='horario',
            field=models.TextField(default=''),
        ),
    ]
