# Generated by Django 4.0.2 on 2022-02-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_puntodeinteres_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='puntodeinteres',
            name='imagenes',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='puntodeinteres',
            name='videos',
            field=models.CharField(default=''),
        ),
    ]
