# Generated by Django 4.0.2 on 2022-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_puntodeinteres_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='horario',
            field=models.TextField(default=''),
        ),
    ]
