# Generated by Django 4.0.2 on 2022-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_puntodeinteres_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='videos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
