# Generated by Django 4.0.2 on 2022-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_puntodeinteres_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('conexiones', models.IntegerField(blank=True, default=0, max_length=20)),
                ('puntodeinteres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.puntodeinteres')),
            ],
        ),
    ]
