# Generated by Django 4.0.2 on 2022-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_beacons'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacons',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
