# Generated by Django 4.0.2 on 2022-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_beacons_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacons',
            name='puntodeinteres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
